### ISSUE TITLE
Values reported during the night are wrong

### ISSUE THREAD

**Issue by MassimoL06** [tetienne/veolia-custom-component#36]
Hello, values returned by Veolia web site are wrong during the night (from midnight to 6 am).
I debugged the code and here are the values returned for december 11th:
**{'daily': [604, 673, 845, 853, 1215, 488, 678, 671, -3042086], 
        'hourly': [13, 17, 17, 2, 0, 13, 21, 15, 118, 20, 2, 14, 0, -147, 3, 0, 0, 0, 26, 350, 0, 15, 79, 93], 
        'last_report_timestamp': 1670454000.0}**
You can see that the last daily value is wrong.

On the same day around 3 pm, I get:
       **{'daily': [604, 673, 845, 853, 1215, 488, 678, 671, 719], 
        'hourly': [13, 17, 17, 2, 0, 13, 21, 15, 118, 20, 2, 4, 0, -147, 3, 0, 0, 0, 26, 350, 0, 15, 79, 93], 
        'last_report_timestamp': 1670454000.0}**

This is triggering a discontinuity on the read values:
![image](https://user-images.githubusercontent.com/118286487/206920879-6b20b9b1-47e0-4306-9146-fda3bfd629b4.png)

The same on the monthly consumption.
May be, in case of negative values, you can return 0.

Another concern is that these values are not the ones of current day but 3 days before.
Is there a way to inject these values in the database on the right day (eg 3 days before) ?
I am thinking about directly injecting the values in the database. Not sure it is possible !

Thanks.

**Comment by tetienne** [comment]
Hi, 

I’ve contacted Veolia about these huge values and negative values. And someone actually call me to explain what happened. That was last year I think.

These strange values are due to bad communication between the counter in front of our house, and the one aggregating all the data from the neighbourhood. In such case, we can get this high values, then to fix this in our report, they then send a negative value.

Currently, in this component, I ignore negative values: https://github.com/tetienne/veolia-custom-component/blob/master/custom_components/veolia/sensor.py#L44 and return None in such case. 0 would be misleading as we don’t know the true value.
